version: '3.8'

services:
  django:
    build:
      context: ./back
    container_name: django-container
    ports:
      - "8000:8000"
    volumes:
      - ./back:/app
    networks:
      - app-network

  nuxt:
    build:
      context: ./front
    container_name: nuxt-container
    ports:
      - "3000:3000"
    volumes:
      - ./front:/app
    depends_on:
      - django
    networks:
      - app-network
networks:
  app-network:
    driver: bridge
